---

- name: "1.1.28.1 | AUDIT | Ensure separate partition exists for /home"
  block:
      - name: "1.1.28.1 | AUDIT | Ensure separate partition exists for /home | Warn if partition is absent"
        debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"
        register: home_mount_absent
        changed_when: home_mount_absent.skipped is undefined

      - name: "1.1.28.1 | AUDIT | Ensure separate partition exists for /home | Present"
        ansible.builtin.import_tasks: warning_facts.yml

  vars:
      warn_control_id: '1.1.28.1'
      required_mount: '/home'
  when:
      - rule_1_1_28_1
      - "'/home' not in mount_names"
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.28.1
      - skip_ansible_lint

# skips if mount is absent
- name: |
    "1.1.28.2 | PATCH | Ensure nodev option set on /home partition
     1.1.28.3 | PATCH | Ensure nosuid option set on /home partition
     1.1.28.4 | PATCH | Ensure usrquota option set on /home partition
     1.1.28.5 | PATCH | Ensure grpquota option set on /home partition"
  mount:
      name: /home
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rule_1_1_28_2 %}nodev,{% endif %}{% if rule_1_1_28_3 %}nosuid,{% endif %}{% if rule_1_1_28_4 %}usrquota,{% endif %}{% if rule_1_1_28_5 %}grpquota{% endif %}
  notify: change_requires_reboot
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - "'/home' in mount_names"
      - item.mount == "/home"
      - rule_1_1_28_1
      - rule_1_1_28_2 or
        rule_1_1_28_3 or
        rule_1_1_28_4 or
        rule_1_1_28_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - rule_1.1.28.2
      - rule_1.1.28.3
      - rule_1.1.28.4
      - skip_ansible_lint
