---

- name: "1.8.1.1 | PATCH | Ensure message of the day is configured properly"
  template:
      src: etc/motd_{{ environments }}.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
  when:
      - rule_1_8_1_1
      - not motd_already_set
  tags:
      - level1-server
      - level1-workstation
      - automated
      - banner
      - patch
      - rule_1.8.1.1

- name: "1.8.1.3 | PATCH | Ensure remote login warning banner is configured properly"
  template:
      src: etc/issue.net.j2
      dest: /etc/issue.net
      owner: root
      group: root
      mode: 0644
  when:
      - rule_1_8_1_3
      - not banner_already_set
  tags:
      - level1-server
      - level1-workstation
      - automated
      - banner
      - patch
      - rule_1.8.1.3

- name: "1.8.1.4 | PATCH | Ensure permissions on /etc/motd are configured"
  file:
      path: /etc/motd
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rule_1_8_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - perms
      - patch
      - rule_1.8.1.4

- name: "1.8.1.5 | PATCH | Ensure permissions on /etc/issue are configured"
  file:
      path: /etc/issue
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rule_1_8_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - perms
      - patch
      - rule_1.8.1.5

- name: "1.8.1.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  file:
      path: /etc/issue.net
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rule_1_8_1_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - perms
      - patch
      - rule_1.8.1.6
