---

# Skips if mount is absent
- name: "1.1.25.1 | AUDIT | Ensure separate partition exists for /var/tmp"
  block:
      - name: "1.1.25.1 | AUDIT | Ensure separate partition exists for /var/tmp | Warn if partition is absent"
        debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"
        register: var_tmp_mount_absent
        changed_when: var_tmp_mount_absent.skipped is undefined

      - name: "1.1.25.1 | AUDIT | Ensure separate partition exists for /var/tmp | Present"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '1.1.25.1'
      required_mount: '/var/tmp'
  when:
      - rule_1_1_25_1
      - "'/var/tmp' not in mount_names"
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.25.1

# skips if mount is absent
- name: |
          "1.1.25.2 | PATCH | Ensure noexec option set on /var/tmp partition"
          "1.1.25.3 | PATCH | Ensure nosuid option set on /var/tmp partition"
          "1.1.25.4 | PATCH | Ensure nodev option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rule_1_1_25_2 %}noexec,{% endif %}{% if rule_1_1_25_4 %}nodev,{% endif %}{% if rule_1_1_25_3 %}nosuid{% endif %}
  notify: change_requires_reboot
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - "'/var/tmp' in mount_names"
      - item.mount == "/var/tmp"
      - rule_1_1_25_1  # This is required so the check takes place
      - rule_1_1_25_2 or
        rule_1_1_25_3 or
        rule_1_1_25_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - skip_ansible_lint
      - rule_1.1.25.2
      - rule_1.1.25.3
      - rule_1.1.25.4
