---

- name: "1.1.23.1 | PATCH | Ensure /tmp is a separate partition"
  block:
      - name: "1.1.23.1 | PATCH | Ensure /tmp is a separate partition | Absent"
        debug:
            msg: "Warning!! {{ required_mount }} is not mounted on a separate partition"

      - name: "1.1.23.1 | PATCH | Ensure /tmp is a separate partition | Present"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '1.1.23.1'
      required_mount: '/tmp'
  when:
      - rule_1_1_23_1
      - "'/tmp' not in mount_names"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.23.1

# via fstab
- name: |
        "1.1.23.2 | PATCH | Ensure nodev option set on /tmp partition"
        "1.1.23.3 | PATCH | Ensure noexec option set on /tmp partition"
        "1.1.23.4 | PATCH | Ensure nosuid option set on /tmp partition"
  mount:
      name: /tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rule_1_1_23_2 %}nodev,{% endif %}{% if rule_1_1_23_3 %}noexec,{% endif %}{% if rule_1_1_23_4 %}nosuid{% endif %}
  notify: remount tmp
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/tmp"
      - not tmp_svc
      - rule_1_1_23_2 or
        rule_1_1_23_3 or
        rule_1_1_23_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - rule_1.1.23.2
      - rule_1.1.23.3
      - rule_1.1.23.4

# via systemd
- name: |
        "1.1.23.1 | PATCH | Ensure /tmp is configured"
        "1.1.23.2 | PATCH | Ensure nodev option set on /tmp partition"
        "1.1.23.3 | PATCH | Ensure noexec option set on /tmp partition"
        "1.1.23.4 | PATCH | Ensure nosuid option set on /tmp partition"
  template:
      src: etc/systemd/system/tmp.mount.j2
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: 0644
  notify: systemd restart tmp.mount
  when:
      - tmp_svc
      - rule_1_1_23_1 or
        rule_1_1_23_2 or
        rule_1_1_23_3 or
        rule_1_1_23_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - mounts
      - rule_1.1.23.1
      - rule_1.1.23.2
      - rule_1.1.23.3
      - rule_1.1.23.4
