---

- name: "1.5.4 | PATCH | Ensure authentication is required when booting into rescue mode"
  lineinfile:
      path: /etc/systemd/system/rescue.service.d/00-require-auth.conf
      regexp: '^ExecStart='
      line: "ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue"
      create: true
      owner: root
      group: root
      mode: 0644
  when:
      - rule_1_5_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.4
