---

- name: "1.7.1.1 | PATCH | Ensure SELinux is installed"
  package:
      name: libselinux
      state: present
  when:
      - rule_1_7_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.1.1

- name: "1.7.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  replace:
      path: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
      replace: ''
  register: selinux_grub_patch
  ignore_errors: true  # noqa ignore-errors
  notify: grub2cfg
  when:
      - rule_1_7_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.7.1.2

- name: "1.7.1.3 | PATCH | Ensure SELinux policy is configured"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ selinux_pol }}"
      state: enforcing
  when:
      - not selinux_disable
      - rule_1_7_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - selinux
      - patch
      - rule_1.7.1.3

- name: "1.7.1.4 | PATCH | Ensure the SELinux state is enforcing"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ selinux_pol }}"
      state: enforcing
  when:
      - not selinux_disable
      - rule_1_7_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - selinux
      - patch
      - rule_1.7.1.4

- name: "1.7.1.5 | AUDIT | Ensure no unconfined services exist"
  block:
      - name: "1.7.1.5 | AUDIT | Ensure no unconfined services exist | Find the unconfined services"
        shell: ps -eZ | grep unconfined_service_t | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
        register: cis_1_7_1_5_unconf_services
        failed_when: false
        changed_when: false

      - name: "1.7.1.5 | AUDIT | Ensure no unconfined services exist | Message on unconfined services"
        debug:
            msg: "Warning!! You have unconfined services: {{ cis_1_7_1_5_unconf_services.stdout_lines }}"
        when: cis_1_7_1_5_unconf_services.stdout | length > 0

      - name: "1.7.1.5 | AUDIT | Ensure no unconfined services exist | warning count"
        ansible.builtin.import_tasks: warning_facts.yml
        when: cis_1_7_1_5_unconf_services.stdout | length > 0
  vars:
      warn_control_id: '1.7.1.5'
  when:
      - rule_1_7_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - services
      - rule_1.7.1.5

- name: "1.7.1.6 | PATCH | Ensure SETroubleshoot is not installed"
  package:
      name: setroubleshoot
      state: absent
  when:
      - rule_1_7_1_6
      - "'setroubleshoot' in ansible_facts.packages"
  tags:
      - level1-server
      - automated
      - selinux
      - patch
      - rule_1.7.1.6

- name: "1.7.1.7 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  package:
      name: mcstrans
      state: absent
  when:
      - rule_1_7_1_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.1.7

- name: "1.7.1.8 | PATCH | Ensure the SELinux mode is not disabled"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ selinux_pol }}"
      state: enforcing
  when:
      - not selinux_disable
      - rule_1_7_1_8
  tags:
      - level1-server
      - level1-workstation
      - auotmated
      - selinux
      - patch
      - rule_1.7.1.8