---

- name: "1.12.1 | PATCH | Ensure GNOME Display Manager is removed"
  package:
      name: gdm
      state: absent
  when:
      - rule_1_12_1
      - "'gdm' in ansible_facts.packages"
      - not gui
  tags:
      - level2-server
      - automated
      - patch
      - gui
      - gdm
      - rule_1.12.1

- name: "1.12.2 | PATCH | Ensure GDM login banner is configured"
  lineinfile:
      path: "{{ item.file }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      create: true
      owner: root
      group: root
      mode: 0644
  notify: reload dconf
  with_items:
      - { file: '/etc/dconf/profile/gdm', regexp: 'user-db', line: 'user-db:user' }
      - { file: '/etc/dconf/profile/gdm', regexp: 'system-db', line: 'system-db:gdm' }
      - { file: '/etc/dconf/profile/gdm', regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }
      - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
      - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: 'banner-message-enable', line: 'banner-message-enable=true' }
      - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: 'banner-message-text', line: "banner-message-text='{{ warning_banner | replace('\n', ' ') }}' " }
  when:
      - rule_1_12_2
      - gui
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - gui
      - gdm
      - rule_1.12.2

- name: "1.12.3 | PATCH | Ensure last logged in user display is disabled"
  lineinfile:
      path: "{{ item.file }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      create: true
      owner: root
      group: root
      mode: 0644
  notify: reload dconf
  with_items:
      - { file: '/etc/dconf/profile/gdm', regexp: 'user-db', line: 'user-db:user' }
      - { file: '/etc/dconf/profile/gdm', regexp: 'system-db', line: 'system-db:gdm' }
      - { file: '/etc/dconf/profile/gdm', regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults'}
      - { file: '/etc/dconf/db/gdm.d/00-login-screen', regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
      - { file: '/etc/dconf/db/gdm.d/00-login-screen', regexp: 'disable-user-list=', line: 'disable-user-list=true' }
  when:
      - rule_1_12_3
      - gui
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - gui
      - rule_1.12.3

- name: "1.12.4 | PATCH | Ensure XDMCP is not enabled"
  lineinfile:
      path: /etc/gdm/custom.conf
      regexp: 'Enable=true'
      state: absent
  when:
      - rule_1_12_4
      - gui
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - gui
      - rule_1.12.4

- name: "1.12.5 | PATCH | Ensure automatic mounting of removable media is disabled"
  lineinfile:
      path: /etc/dconf/db/local.d/00-media-automount
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      create: true
      owner: root
      group: root
      mode: 0640
  notify: reload dconf
  with_items:
      - { regex: '\[org\/gnome\/desktop\/media-handling\]', line: '[org/gnome/desktop/media-handling]' }
      - { regex: 'automount=', line: 'automount=false' }
      - { regex: 'automount-open=', line: 'automount-open=false'}
  when:
      - rule_1_12_5
      - gui
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - gui
      - rule_1.12.5
