---

- name: "SECTION | 1.1.1.x | Disable unused filesystems"
  import_tasks: cis_1.1.1.x.yml

- name: "SECTION | 1.1.23.x | Configure /tmp"
  import_tasks: cis_1.1.23.x.yml

- name: "SECTION | 1.1.24.x | Configure /var"
  import_tasks: cis_1.1.24.x.yml

- name: "SECTION | 1.1.25.x | Configure /var/tmp"
  import_tasks: cis_1.1.25.x.yml

- name: "SECTION | 1.1.26.x | Configure /var/log"
  import_tasks: cis_1.1.26.x.yml

- name: "SECTION | 1.1.27.x | Configure /var/log/audit"
  import_tasks: cis_1.1.27.x.yml

- name: "SECTION | 1.1.28.x | Configure /home"
  import_tasks: cis_1.1.28.x.yml

- name: "SECTION | 1.1.29.x | Configure /dev/shm"
  import_tasks: cis_1.1.29.x.yml

- name: "SECTION | 1.1.x | Disable various mounting"
  import_tasks: cis_1.1.x.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  import_tasks: cis_1.2.x.yml

- name: "SECTION | 1.4 | Filesystem Integrity Checking"
  import_tasks: cis_1.4.x.yml
  when: config_aide

- name: "SECTION | 1.5 | Secure Boot Settings"
  import_tasks: cis_1.5.x.yml

- name: "SECTION | 1.6 | Additional Process Hardening"
  import_tasks: cis_1.6.x.yml

- name: "SECTION | 1.7 | Mandatory Access Control"
  import_tasks: cis_1.7.1.x.yml
  when: not selinux_disable

- name: "SECTION | 1.8 | Command Line Warning Banners"
  import_tasks: cis_1.8.1.x.yml

- name: "SECTION | 1.9 | Updates and Patches"
  import_tasks: cis_1.9.yml

- name: "SECTION | 1.10 | Crypto policies"
  import_tasks: cis_1.10.yml
  when:
  - not system_is_ec2

- name: "SECTION | 1.12 | Gnome Display Manager"
  import_tasks: cis_1.12.x.yml