---

- name: "2.2.1 | PATCH | Ensure xinetd is not installed"
  package:
      name: xinetd
      state: absent
  when:
      - rule_2_2_1
      - not xinetd_server
      - "'xinetd' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.1

- name: "2.2.1.1 | PATCH | Ensure time synchronization is in use"
  package:
      name: "{{ time_synchronization }}"
      state: present
  when:
      - rule_2_2_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.1.1

- name: "2.2.1.2 | PATCH | Ensure chrony is configured"
  block:
      - name: "2.2.1.2 | PATCH | Ensure chrony is configured | Set configuration"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.2.1.2 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
        lineinfile:
            path: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            create: true
            mode: 0644
  when:
      - time_synchronization == "chrony"
      - rule_2_2_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.2
