---

- name: "2.2.3 | PATCH | Ensure rsync service is not enabled "
  package:
      name: rsync
      state: absent
  when:
      - not rsync_server
      - "'rsync' in ansible_facts.packages"
      - rule_2_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rsync
      - rule_2.2.3

- name: "2.2.4 | PATCH | Ensure Avahi Server is not installed"
  package:
      name:
          - avahi-autoipd
          - avahi
      state: absent
  when:
      - rule_2_2_4
      - not avahi_server
      - "'avahi' in ansible_facts.packages or 'avahi-autopd' in ansible_facts.packages"
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - avahi
      - rule_2.2.4

- name: "2.2.5 | PATCH | Ensure net-snmp is not installed"
  package:
      name: net-snmp
      state: absent
  when:
      - not net_snmp_server
      - "'net-snmp' in ansible_facts.packages"
      - rule_2_2_5
  tags:
      - level1-server
      - level1-workstation
      - automation
      - patch
      - snmp
      - rule_2.2.5

- name: "2.2.6 | PATCH | Ensure HTTP Proxy Server is not installed"
  package:
      name: squid
      state: absent
  when:
      - not squid_server
      - "'squid' in ansible_facts.packages"
      - rule_2_2_6
  tags:
      - level1-server
      - level1-workstation
      - automation
      - patch
      - squid
      - rule_2.2.6

- name: "2.2.7 | PATCH | Ensure Samba is not enabled"
  package:
      name: samba
      state: absent
  when:
      - not samba_server
      - "'samba' in ansible_facts.packages"
      - rule_2_2_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - samba
      - rule_2.2.7

- name: "2.2.8 | PATCH | Ensure IMAP and POP3 server is not installed"
  package:
      name:
          - dovecot
          - cyrus-imapd
      state: absent
  when:
      - not dovecot_cyrus_server
      - "'dovecot' in ansible_facts.packages or 'cyrus-imapd' in ansible_facts.packages"
      - rule_2_2_8
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - dovecot
      - imap
      - pop3
      - rule_2.2.8

- name: "2.2.9 | PATCH | Ensure a web server is not installed"
  block:
      - name: "2.2.9 | PATCH | Ensure a web server is not installed | Remove httpd server"
        package:
            name: httpd
            state: absent
        when:
            - not httpd_server
            - "'httpd' in ansible_facts.packages"

      - name: "2.2.9 | PATCH | Ensure a web server is not installed | Remove nginx server"
        package:
            name: nginx
            state: absent
        when:
            - not nginx_server
            - "'nginx' in ansible_facts.packages"
  when:
      - rule_2_2_9
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - httpd
      - nginx
      - webserver
      - rule_2.2.9

- name: "2.2.10 | PATCH | Ensure FTP Server is not installed"
  package:
      name: ftp
      state: absent
  when:
      - not ftp_server
      - "'ftp' in ansible_facts.packages"
      - rule_2_2_10
  tags:
      - level1-server
      - level1-workstation
      - automation
      - patch
      - ftp
      - rule_2.2.10

- name: "2.2.11 | PATCH | Ensure DNS Server is not installed"
  package:
      name: bind
      state: absent
  when:
      - not dns_server
      - "'bind' in ansible_facts.packages"
      - rule_2_2_11
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - dns
      - rule_2.2.11

- name: "2.2.12 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked"
  systemd:
      name: nfs-utils
      masked: true
      state: stopped
  when:
      - not nfs_server
      - "'nfs-utils' in ansible_facts.packages"
      - rule_2_2_12
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - nfs
      - services
      - rule_2.2.12

- name: "2.2.13 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked"
  systemd:
      name: "{{ item }}"
      masked: true
      state: stopped
  with_items:
      - rpcbind
      - rpcbind.socket
  when:
      - not rpc_server
      - "'rpcbind' in ansible_facts.packages"
      - rule_2_2_13
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rpc
      - rule_2.2.13

- name: "2.2.14 | PATCH | Ensure LDAP Server is not installed"
  package:
      name: openldap-servers
      state: absent
  when:
      - not openldap-servers
      - "'openldap-servers' in ansible_facts.packages"
      - rule_2_2_14
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - ldap
      - rule_2.2.14

- name: "2.2.15 | PATCH | Ensure DHCP Server is not installed"
  package:
      name: dhcp-server
      state: absent
  when:
      - not dhcp_server
      - "'dhcp-server' in ansible_facts.packages"
      - rule_2_2_15
  tags:
      - level1-server
      - level1-workstation
      - audtomated
      - patch
      - dhcp
      - rule_2.2.15

- name: "2.2.16 | PATCH | Ensure CUPS is not installed"
  package:
      name: cups
      state: absent
  when:
      - not cups_server
      - "'cups' in ansible_facts.packages"
      - rule_2_2_16
  tags:
      - level1-server
      - automated
      - patch
      - cups
      - rule_2.2.16

- name: "2.2.17 | PATCH | Ensure NIS Server is not installed"
  package:
      name: ypserv
      state: absent
  when:
      - not nis_server
      - "'ypserv' in ansible_facts.packages"
      - rule_2_2_17
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - nis
      - rule_2.2.17

- name: "2.2.18 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      path: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify: restart postfix
  when:
      - not is_mail_server
      - "'postfix' in ansible_facts.packages"
      - rule_2_2_18
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - postfix
      - rule_2.2.18