---

- name: "2.3.1 | PATCH | Ensure NIS Client is not installed"
  package:
      name: ypbind
      state: absent
  when:
      - not ypbind_required
      - "'ypbind' in ansible_facts.packages"
      - rule_2_3_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - nis
      - rule_2.3.1

- name: "2.3.2 | PATCH | Ensure telnet client is not installed"
  package:
      name: telnet
      state: absent
  when:
      - not telnet_required
      - "'telnet' in ansible_facts.packages"
      - rule_2_3_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - telnet
      - rule_2.3.2

- name: "2.3.3 | PATCH | Ensure LDAP client is not installed"
  package:
      name: openldap-clients
      state: absent
  when:
      - not openldap_clients_required
      - "'openldap-clients' in ansible_facts.packages"
      - rule_2_3_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - ldap
      - rule_2.3.3

- name: "2.3.4 | PATCH | Ensure TFTP client is not installed"
  package:
      name: tftp
      state: absent
  when:
      - not tftp_client
      - "'tftp' in ansible_facts.packages"
      - rule_2_3_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - tftp
      - rule_2.3.4
