---

- name: "5.5.2 | PATCH | Ensure system accounts are secured"
  block:
      - name: "5.5.2 | Ensure system accounts are secured | Set nologin"
        user:
            name: "{{ item.id }}"
            shell: /usr/sbin/nologin
        with_items:
            - "{{ passwd }}"
        when:
            - item.id != "root"
            - item.id != "sync"
            - item.id != "shutdown"
            - item.id != "halt"
            - item.uid < uid_interactive_uid_start | int
            - item.shell != "/bin/false"
            - item.shell != "/usr/sbin/nologin"
        loop_control:
            label: "{{ item.id }}"

      - name: "5.5.2 | PATCH | Ensure system accounts are secured | Lock accounts"
        user:
            name: "{{ item.id }}"
            password_lock: true
        with_items:
            - "{{ passwd }}"
        when:
            - item.id != "halt"
            - item.id != "shutdown"
            - item.id != "sync"
            - item.id != "root"
            - item.id != "nfsnobody"
            - item.uid < uid_interactive_uid_start | int
            - item.shell != "/bin/false"
            - item.shell != "/usr/sbin/nologin"
        loop_control:
            label: "{{ item.id }}"
  when:
      - rule_5_5_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - accounts
      - rule_5.5.2

- name: "5.5.3 | PATCH | Ensure default user shell timeout is 900 seconds or less"
  blockinfile:
      path: "{{ item.path }}"
      state: "{{ item.state }}"
      create: true
      mode: 0644
      marker: "# {mark} ANSIBLE MANAGED"
      block: |
        TMOUT={{ shell_session_timeout.timeout }}
        export TMOUT
        readonly TMOUT
  with_items:
      - { path: "{{ shell_session_timeout.file }}", state: present }
      - { path: /etc/profile, state: "{{ (shell_session_timeout.file == '/etc/profile') | ternary('present', 'absent') }}" }
  when:
      - rule_5_5_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - accounts
      - rule_5.5.3

- name: "5.5.4 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: false
  failed_when: false
  when:
      - rule_5_5_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - accounts
      - rule_5.5.4

- name: "5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive"
  block:
      - name: "5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive | Set umask for /etc/login.defs pam_umask settings"
        replace:
            path: /etc/login.defs
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
        loop:
            - { regexp: '(UMASK\s+)0[012][0-6]', replace: '\1 027' }
            - { regexp: '(USERGROUPS_ENAB\s+)yes', replace: '\1 no' }

      - name: "5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive | Set umask for /etc/bashrc"
        replace:
            path: /etc/bashrc
            regexp: '(^\s+umask) 0[012][0-6]'
            replace: '\1 027'

      - name: "5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive | Set umask for /etc/profile"
        replace:
            path: /etc/profile
            regexp: '(^\s+umask) 0[012][0-6]'
            replace: '\1 027'
  when:
      - rule_5_5_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - accounts
      - rule_5.5.5
