---

- name: "3.4.1.1 | PATCH | Ensure firewalld is installed"
  package:
      name:
          - firewalld
          - iptables
      state: present
  when:
      - rule_3_4_1_1
      - firewall == "firewalld"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - firewalld
      - rule_3.4.1.1

- name: "3.4.2.1 | PATCH | Ensure firewalld service is enabled and running"
  systemd:
      name: firewalld
      state: started
      enabled: true
  when:
      - firewall == "firewalld"
      - rule_3_4_2_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - firewalld
      - rule_3_4_2_1

- name: "3.4.2.2 | PATCH | Ensure iptables-services not installed with firewalld"
  block:
      - name: "3.4.2.2 | PATCH | Ensure iptables-services not installed with firewalld | Stop running services"
        systemd:
            name: "{{ item }}"
            masked: true
        with_items:
            - iptables
            - ip6tables
        when: item in ansible_facts.packages

      - name: "3.4.2.2 | PATCH | Ensure iptables-services not installed with firewalld | Remove IPTables"
        package:
            name: iptables-services
            state: absent
  when:
      - rule_3_4_2_2
      - firewall == "firewalld"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - firewalld
      - rule_3.4.2.2

- name: "3.4.2.3 | PATCH | Ensure nftables either not installed or masked with firewalld"
  systemd:
      name: nftables
      state: stopped
      masked: true
  when:
      - firewall == "firewalld"
      - rule_3_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - firewalld
      - rule_3_4_2_3

- name: "3.4.2.4 | PATCH | Ensure firewalld default zone is set"
  block:
      - name: "3.4.2.4 | AUDIT | Ensure firewalld default zone is set"
        shell: "firewall-cmd --get-default-zone | grep {{ default_zone }}"
        changed_when: false
        failed_when: ( firewalld_zone_set.rc not in [ 0, 1 ] )
        register: firewalld_zone_set

      - name: "3.4.2.4 | AUDIT | Ensure firewalld default zone is set"
        command: firewall-cmd --set-default-zone="{{ default_zone }}"
        when:
            - firewalld_zone_set.rc != 0
  when:
      - firewall == "firewalld"
      - rule_3_4_2_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - firewalld
      - rule_3.4.2.4

- name: "3.4.2.5 | AUDIT | Ensure network interfaces are assigned to appropriate zone"
  block:
      - name: "3.4.2.5 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies"
        shell: "nmcli -t connection show | awk -F: '{ if($4){print $4} }' | while read INT; do firewall-cmd --get-active-zones | grep -B1 $INT; done"
        changed_when: false
        failed_when: false
        check_mode: false
        register: cis_3_4_2_5_interfacepolicy

      - name: "3.4.2.5 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies | Show the interface to policy"
        debug:
            msg:
                - "Warning!! The items below are the policies tied to the interfaces, please correct as needed"
                - "{{ cis_3_4_2_5_interfacepolicy.stdout_lines }}"

      - name: "3.4.2.5 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '3.4.2.5'
  when:
      - firewall == "firewalld"
      - rule_3_4_2_5
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.4.2.5

- name: "3.4.2.6 | AUDIT | Ensure firewalld drops unnecessary services and ports"
  block:
      - name: "3.4.2.6 | AUDIT | Ensure firewalld drops unnecessary services and ports | Get list of services and ports"
        shell: "firewall-cmd --get-active-zones | awk '!/:/ {print $1}' | while read ZN; do firewall-cmd --list-all --zone=$ZN; done"
        changed_when: false
        failed_when: false
        check_mode: false
        register: cis_3_4_2_6_servicesport

      - name: "3.4.2.6 | AUDIT | Ensure firewalld drops unnecessary services and ports | Show services and ports"
        debug:
            msg:
                - "The items below are the services and ports that are accepted, please correct as needed"
                - "{{ cis_3_4_2_6_servicesport.stdout_lines }}"
  when:
      - firewall == "firewalld"
      - rule_3_4_2_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.4.2.6
