---

- name: "SECTION | 3.1.x | Network Parameters (Host Only)"
  import_tasks: cis_3.1.x.yml

- name: "SECTION | 3.2.x | Network Parameters (Host and Router)"
  import_tasks: cis_3.2.x.yml

- name: "SECTION | 3.3.x | Uncommon Network Protocols"
  import_tasks: cis_3.3.x.yml

- name: "SECTION | 3.4.1.x | Configure firewalld"
  import_tasks: cis_3.4.1.x.yml
  when:
      - firewall == "firewalld"

- name: "SECTION | 3.4.3.x | Configure nftables"
  import_tasks: cis_3.4.3.x.yml
  when:
      - firewall == "nftables"

- name: "SECTION | 3.4.6.x | Disable IPv6"
  import_tasks: cis_3.4.6.x.yml
    when:
      - not ipv6_required